on:
  workflow_dispatch:
name: Auto-Build
env:
  MOSH_TAG: 1.4.0+blink-17.3.0
jobs:

  linux-build:
    name: Linux Build
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        architecture: [armhf]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build container for ${{ matrix.architecture }}
        run: | 
          docker build -t builder --build-arg TARGET_ARCH=${{ matrix.architecture }} .

      - run: git clone --depth=1 --branch mosh-$MOSH_TAG https://github.com/blinksh/mosh-server.git mosh

      - name: Build binaries for ${{ matrix.architecture }}
        run: docker run -v $PWD/mosh:/mosh -w /mosh --name=builder builder sh -c 'git config --global --add safe.directory /mosh && git describe --dirty --always && ./autogen.sh && LDFLAGS=-static ./configure && make V=1 && cat VERSION.stamp'

      - name: Test run mosh-server
        run: docker run -v $PWD/mosh:/mosh -w /mosh/src/frontend builder sh -c 'chmod +x mosh-server && ./mosh-server'

      - name: Rename binaries
        run: |
          mv mosh/src/frontend/mosh-server mosh/src/frontend/mosh-server-$MOSH_TAG-linux-${{ matrix.architecture }}
          mv mosh/src/frontend/mosh-client mosh/src/frontend/mosh-client-$MOSH_TAG-linux-${{ matrix.architecture }}
      
      - uses: actions/upload-artifact@v4
        with:
          name: mosh-server-${{ env.MOSH_TAG }}-linux-${{ matrix.architecture }}
          path: mosh/src/frontend/mosh-server-${{ env.MOSH_TAG }}-linux-${{ matrix.architecture }}
          if-no-files-found: error

      - uses: actions/upload-artifact@v4
        with:
          name: mosh-client-${{ env.MOSH_TAG }}-linux-${{ matrix.architecture }}
          path: mosh/src/frontend/mosh-client-${{ env.MOSH_TAG }}-linux-${{ matrix.architecture }}
          if-no-files-found: error

  release:
    name: Release
    needs: [linux-build]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v4
      
      - name: Create release description
        run: |
          (
            echo '- [Workflow file](https://github.com/${{ github.repository }}/blob/${{ github.sha }}/.github/workflows/autobuild.yml)'
            echo
            echo '## Files'
            echo '### Linux'
            echo '```'
            (
              for dir in mosh-client-$MOSH_TAG-linux* mosh-server-$MOSH_TAG-linux*; do
                cd "$dir"
                for prog in mosh*; do
                  file "$prog"
                done
                cd ..
              done
            )
            echo '```'
            echo
            echo '## SHA256 Checksums'
            echo '```'
            (
              for dir in mosh-client* mosh-server*; do
                cd "$dir"
                for prog in mosh*; do
                  sha256sum "$prog"
                done
                cd ..
              done
            )
            echo '```'
          ) | tee release.md
      
      - id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: release.md
          path: release.md
          if-no-files-found: error

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: "${{ env.MOSH_TAG }}"
          tag_name: ${{ env.MOSH_TAG }}
          prerelease: false
          draft: false
          body_path: release.md
          files: |
            mosh-client-*/mosh-client*
            mosh-server-*/mosh-server*

